id: I008C341F
source: ''
source_file: null
initial_creation_type: input
imported: '2022-08-15T16:35:00.830347'
last_modified: '2022-08-15T16:35:00.830364'
parser: null
source_metadata: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
ocr_word_median_confidence_index: null
base: {}
